Repository browser-history/browser-history, pull requests merged in 2020-09, with the labels that each got.

#16 [CLI] Add basic CLI
  .pylintrc
  browser_history/cli.py
  docs/cli.rst
  docs/conf.py
  docs/index.rst
  docs/quickstart.rst
  docs/requirements.txt
  setup.py
Labels: enhancement

#24 [CODE] Add Edge support for Windows #1
  browser_history/browsers.py
  browser_history/cli.py
  tests/test_browsers.py
  tests/test_homedirs/Windows/AppData/Local/Microsoft/Edge/User Data/Profile 1/History
  tests/test_homedirs/Windows/AppData/Local/Microsoft/Edge/User Data/Profile 2/History
Labels: browser-support

#29 Migrate get_history from utils to __init__ and Fix documentation
  README.md
  browser_history/__init__.py
  browser_history/cli.py
  browser_history/utils.py
  docs/quickstart.rst
Labels: refactor

#37 [ENHANCEMENT]Added foundation for exporting output to file
  browser_history/cli.py
  browser_history/generic.py
Labels: enhancement
