Repository browser-history/browser-history, pull requests merged in 2020-10, with the labels that each got.

#61 [FEATURE] add Windows and Mac OS to workflow
  .github/workflows/python-package.yml
Labels: enhancement

#66 [CODE] Add support for Brave Browser on Linux
  browser_history/browsers.py
Labels: browser-support

#69 [Feature Added] Mac OS support added for Brave,Opera,Edge
  browser_history/browsers.py
  browser_history/generic.py
Labels: browser-support, hacktoberfest-accepted

#75 [DOC] Document Outputs class
  docs/API.rst
  docs/outputs.rst
  tests/test_generic.py
Labels: documentation, hacktoberfest-accepted

#78 save() function in Outputs
  browser_history/cli.py
  browser_history/generic.py
Labels: enhancement, hacktoberfest-accepted

#77 [DOCS] Outputs class
  browser_history/generic.py
  docs/conf.py
  docs/requirements.txt
Labels: hacktoberfest-accepted, refactor

#82 [CLI] Use logger for CLI errors (#79)
  browser_history/cli.py
Labels: enhancement, hacktoberfest-accepted

#76 Bookmarks, some refactor and README update
  README.md
  browser_history/__init__.py
  browser_history/browsers.py
  browser_history/cli.py
  browser_history/generic.py
  browser_history/utils.py
  docs/conf.py
  docs/quickstart.rst
  docs/requirements.txt
  tests/test_browsers.py
  tests/test_generic.py
Labels: documentation, enhancement, priority: high, refactor
