Repository browser-history/browser-history, pull requests merged in 2020-11, with the labels that each got.

#92 [CLI] Fix incorrect error message for invalid types
  browser_history/cli.py
Labels: bug, hacktoberfest-accepted

#93 [TESTS] Remove test suite dependence on run directory
  tests/utils.py
Labels: hacktoberfest-accepted, priority: medium

#94 [TESTS] Timezone awareness for history datetime comparison
  .github/workflows/python-package.yml
  tests/test_browsers.py
  tests/utils.py
Labels: hacktoberfest-accepted

#89 [DOC] Browser class
  .github/workflows/python-docs.yml
  .github/workflows/python-mypy.yml
  browser_history/browsers.py
  browser_history/generic.py
  docs/functionality.rst
Labels: documentation, enhancement, hacktoberfest-accepted
